including binaries

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -27,27 +27,16 @@ if [[ -z "${CONFLUENT_VERSION}" ]]; then
     exit 1
 fi
 
-ARCHIVE_URL=${ARCHIVE_URL_OVERRIDE:-http://packages.confluent.io/archive/5.2/confluent-${CONFLUENT_VERSION}-2.12.tar.gz}
-wget -qO - $ARCHIVE_URL | tar -zxf -
-if ! [ $? ]; then
-    echo "FAILED to obtain confluent distribution" | indent
-    exit 1
-fi
+#ARCHIVE_URL=${ARCHIVE_URL_OVERRIDE:-http://packages.confluent.io/archive/5.2/confluent-${CONFLUENT_VERSION}-2.12.tar.gz}
+#wget -qO - $ARCHIVE_URL | tar -zxf -
+#if ! [ $? ]; then
+#    echo "FAILED to obtain confluent distribution" | indent
+#    exit 1
+#fi
 
-cp -a confluent-${CONFLUENT_VERSION}/* $BUILD_DIR/
+#cp -a confluent-${CONFLUENT_VERSION}/* $BUILD_DIR/
 
 echo "Copied Confluent ${CONFLUENT_VERSION} successfully" | indent
-
-rm -rf confluent-${CONFLUENT_VERSION}/share/ksql
-rm -rf confluent-${CONFLUENT_VERSION}/share/doc
-rm -rf confluent-${CONFLUENT_VERSION}/java/kafka-connect-elasticsearch
-rm -rf confluent-${CONFLUENT_VERSION}/java/kafka-connect-s3
-rm -rf confluent-${CONFLUENT_VERSION}/java/kafka-connect-hdfs
-rm -rf confluent-${CONFLUENT_VERSION}/java/kafka-connect-activemq
-rm -rf confluent-${CONFLUENT_VERSION}/java/kafka-connect-imbmq
-rm -rf confluent-${CONFLUENT_VERSION}/java/kafka-connect-jms
- 
-ls -lf confluent-${CONFLUENT_VERSION}
 
 CONFLUENT_COMPONENT=$(cat ${ENV_DIR}/CONFLUENT_COMPONENT)
 
